site_name: Annie.io
site_description: Blazingly fast Approximate Nearest Neighbors in Rust
site_url: https://annie-docs.netlify.app/
repo_url: https://github.com/Programmers-Paradise/Annie-docs
repo_name: Programmers-Paradise/Annie-docs
edit_uri: edit/main/docs/


theme:
  name: material
  logo: assets/logo.png  
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.code.highlight
    - content.code.line_numbers
    - palette.toggle
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Fira Code

nav:
  - Home: index.md
  - API Reference:
    - AnnIndex: api/ann_index.md
    - PyHnswIndex: api/hnsw_index.md
    - ThreadSafeAnnIndex: api/threadsafe_index.md
    - Python API:
        - rust_annie: api/python/rust_annie/index.html

  - Features:
    - Concurrency: concurrency.md
    - Filtered Search: filtering.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false

plugins:
  - search

# Copy extra files to site directory
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Programmers-Paradise/Annie
      name: GitHub
  
# Directory where the documentation source files are located
docs_dir: docs

# Directory where the built site will be located
site_dir: site
